<?php

use App\Http\Controllers\BookController;
use Illuminate\Support\Facades\Route;

// // Authentication routes (generated by laravel/ui)
// Auth::routes();

// // Protected routes for books
// Route::middleware('auth')->group(function () {
//     Route::resource('books', BookController::class)->only(['index', 'create', 'store']);
// });

// // Home route
// Route::get('/', function () {
//     return view('welcome');
// });
// ?>